import pdb
from typing import Any, Callable, List

class PdbDetach(pdb.Pdb):
    _precmd_handlers: List[Callable[[str], str]] = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def do_detach(self, arg: str) -> bool: ...
    def precmd(self, line: str) -> str: ...
    def attach_precmd_handler(self, handler: Callable[[str], str]) -> None: ...

def precmd_logger(line: str) -> str: ...
