from pdb_attach.detach import PdbDetach as PdbDetach
from pdb_attach.pdb_socket import PdbServer as PdbServer
from typing import Any, Union

class PdbSelect(PdbServer, PdbDetach):
    def __init__(self, port: Union[int, str], *args: Any, **kwargs: Any) -> None: ...
    def __del__(self) -> None: ...
    @classmethod
    def listen(cls, port: Union[int, str], *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def unlisten(cls) -> None: ...
    def do_detach(self, arg: str) -> bool: ...
