import pdb
from types import FrameType
from typing import Any, Callable, List, Union

__version__: str
_original_handler: Any
PDB_PROMPT: str

class PdbDetach(pdb.Pdb):
    use_rawinput: bool = ...
    _precmd_handlers: List[Callable[[str], str]] = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    trace_dispatch: Any = ...
    def do_detach(self, arg: str) -> bool: ...
    def precmd(self, line: str) -> str: ...
    def attach_precmd_handler(self, handler: Callable[[str], str]) -> None: ...

def precmd_logger(line: str) -> str: ...
def _handler(port: int, signum: int, frame: FrameType) -> None: ...
def listen(port: Union[int, str]) -> None: ...
def unlisten() -> None: ...
